### PR TITLE
Shift-left and shift-right clicking on exchange blocks to change amounts.

### PR DESCRIPTION
**Pull request by shadowjay1**
amounts.

### CODE REVIEW

**Comment by gmlaxfanatic** [comment]
I don't believe this will do anything. I believe you will have to remove the RuleBlock that was representing that exchange rule and then replace it with a new RuleBlock containing the updated amount.

**Comment by shadowjay1** [comment]
Hm, I was looking at SetCommand.java, and that was all that it seemed to do. I'll investigate a bit more.

**Comment by gmlaxfanatic** [comment]
So I haven't thoroughly bug tested all those different commands, so my code for the set command might not work... Most of my testing has been using the /iecreate command and then making sure the items exchange properly.

**Comment by shadowjay1** [comment]
I think my latest commit should fix it.

**Pull request merged**
