### PR TITLE
Fix stuff.

### PR DESCRIPTION
**Pull request by shadowjay1**

### CODE REVIEW

**Comment by gmlaxfanatic** [comment]
Side note: People (Pruby) have complained when I casted a new object when initiating variables, apparently the syntax is not backwards compatible with previous java versions (he was using one), so we might want to stay away from that, but it personally fine with me.

What you have been using

> public static final Map<ItemStack, String> MATERIAL_NAME = new HashMap<ItemStack, String>()

What is backwards compatible

> public static final Map<ItemStack, String> MATERIAL_NAME = new HashMap<>()

**Comment by shadowjay1** [comment]
Whivh versions of Java don't support this?

**Comment by gmlaxfanatic** [comment]
Hah, I was remembering it backwards, what you are doing is backwards compatible and what I am doing is not. My bad.
java version 6 doesn't support the <> notation.

**Comment by shadowjay1** [comment]
So, now we just need to test on Civtest and for someone to make a tutorial video, then we're good for Civcraft?

**Comment by gmlaxfanatic** [comment]
About right, and fixing all the small bugs that are sure to be found. I'm sure ttk will want pretty exhaustive testing, since its a fairly important plugin we are replacing, so don't expect it to go up on the main server that quickly.

**Comment by gmlaxfanatic** [comment]
I'm headed off to sleep, I found a few bugs over in the issues page if you want to check them out. I'm putting an updated jar up on CivTest.

**Pull request merged**
